### PR TITLE
Add Dimension.ORIGIN

### PR DESCRIPTION
**Pull request by adolski**
I see that the `Dimension` enum's days may be numbered (#187), but this is a quick fix to be able to add `Origin` to the `Vary` header.

### CODE REVIEW

**Comment by jlouvel** [comment]
Thanks for the contribution, looks good to me. @thboileau what do you think?

**Comment by thboileau** [comment]
hello @adolski 
yes, it looks good to me.

In order to integrate your contribute we need that you sign the Joint Copyright Assignment document.
Could you read [this](https://github.com/restlet/restlet-framework-java/wiki/Contribute#submit-contributions) and return the signed JCA?

thanks for your interest in Restlet framework

**Comment by adolski** [comment]
JCA submitted. Thanks!

**Comment by thboileau** [comment]
@adolski 

Thanks for your contribution. It is now part of Restlet Framework 2.3, and will be shipped with version 2.3.11.

**Pull request closed without merging**
