### PR TITLE
2.5 nio depreciation

### PR DESCRIPTION
**Pull request by jlouvel**
## The aim

Deprecated NIO flavor of Restlet API for removal in next major release, with plan to use
virtual threads instead to achieve additional scalability and reactive behavior.

## The solution
Marked related code as deprecated.

* PR size
    * [x] Under 300 lines :white_check_mark:
    * [ ] Can't be split without complicating the process even more
* Tests
    * [ ] Added
    * [x] Not applicable (why?)
* Doc
    * [x] Added
    * [ ] Not applicable
* Reviewer
    * [x] Asked for a review
    * [ ] Added label `DO NOT REVIEW`

### CODE REVIEW

**Review by thboileau — APPROVED** [review]
LGTM

**Comment by kerbymart** [comment]
Hi @jlouvel which version supports virtual threads?

**Comment by jlouvel** [comment]
Hi @kerbymart We are releasing 2.6.0 version later this month, then starting with the 2.7/3.0 branch where we can work on such innovations. Let us know if/how you are interested to contribute. https://github.com/restlet/restlet-framework-java/wiki/Roadmap

**Comment by kerbymart** [comment]
@jlouvel if I can better understand Restlet architecture, why not. But there's no sufficient documentation atm. Materials like architectural, sequence and other UML diagrams.

**Comment by jlouvel** [comment]
@kerbymart Did you get a chance to read the "Restlet in Action" book published by Manning? I think that would cover a lot of that ground for you, including UML diagrams

**Comment by kerbymart** [comment]
@jlouvel Okay, I’ll take a look. I can’t quite remember how I first learned to use Restlet over a decade ago, but it’s been my go-to framework for building anything web-related ever since. I’d say I’m at a user-level understanding of the framework, but I’ve also learned how to wire things together effectively. Over the years, I’ve run into plenty of bugs and errors, and I’ve managed to work around them without needing to touch the internal code.

**Comment by jlouvel** [comment]
Thanks @kerbymart for the feedback on your long journey with the framework! It would be great if you could get involved more with the internals. Let us know how we can help

**Pull request merged**
