### PR TITLE
Basic Android compatibility for JAX-RS extension

### PR DESCRIPTION
**Pull request by curioustechizen**
Added basic Android compatibility for JAX-RS extension. The procedure followed was:

  - Remove all providers that had dependencies on javax.* libraries (jaxb, javax.mail ...). **Note:** This was done only for Android edition using `<excludes>` in `module.xml`.
  - Created a `SimpleXmlProvider` utilizing [Simple XML framework](http://simple.sourceforge.net/)
  - Added this new provider in `JaxRsRestlet`

This generates a version of org.restlet.ext.jaxrs.jar that is usable on Android. With the NIO extension one can easily create JAX-RS **servers** on Android.

### Limitations:

  - No replacement (yet) for Multipart Provider. Can easily be added via [okhttp](https://github.com/square/okhttp) though.

### CODE REVIEW

**Comment by jlouvel** [comment]
Thanks a lot for your contribution!

Could you send us the signed JCA?
https://github.com/restlet/restlet-framework-java/wiki/Contribute

Note that we are replacing the NIO extension by Netty 4.1 in next RF version (3.0), but Netty 4.1 is also compatible with Android:
http://netty.io/wiki/new-and-noteworthy-in-4.1.html

**Comment by curioustechizen** [comment]
@jlouvel Sent the signed JCA.

Thanks for the heads up about NIO extension being replaced with Netty extension. Maybe I'll wait for that before I write the blog post I was planning about using Restlet to create a RESTful server on Android :)

**Comment by thboileau** [comment]
Thanks a lot Kiran for your contribution!

**Comment by curioustechizen** [comment]
@thboileau You're welcome and thanks to Restlet Inc for this amazing framework that makes writing RESTful web services a breeze!

BTW, will these changes be merged into the 3.0 branch as well? Or should I send in a separate PR for integrating Android support into 3.0?

**Comment by jlouvel** [comment]
Thanks for the signed JCA, I confirm we received it. Sounds good for waiting the Netty support for the blog post. I'll let @thboileau answer regarding the need for a second PR.

**Pull request merged**
