### PR TITLE
Use an address for the InetSocketAddress if provided

### PR DESCRIPTION
**Pull request by bquintanaj**
Use getHelped().getAddress() for the server. Also, for the sake of consistency, use the same steps for HttpsServerHelper

### CODE REVIEW

**Comment by bquintanaj** [comment]
Hmmm... there seems to be a timing problem somewhere, because locally sometimes I get successful builds, and other times I get
```
 <failure message="expected:&lt;OK (200) - The request has succeeded&gt; but was:&lt;Communication Error (1001) - The connector failed to complete the communication with the server&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;OK (200) - The request has succeeded&gt; but was:&lt;Communication Error (1001) - The connector failed to complete the communication with the server&gt;
    at org.restlet.test.representation.DigesterRepresentationTestCase.testGet(DigesterRepresentationTestCase.java:137)
</failure>
```

**Comment by thboileau** [comment]
Hello @bquintanaj 
Thanks a lot for your contribution, it is very clear and will be promptly approved.
We would like to know if you can send us the signed JCA : https://github.com/restlet/restlet-framework-java/wiki/Contribute#submit-contributions.

This will allows us to add your contribution to the framework.

Best regards,
Thierry Boileau

**Comment by bquintanaj** [comment]
Hi @thboileau, I've sent already the signed JCA. Please let me know if there's a problem.
On the other hand, I haven't been able to solve the failing test yet. I haven't been able to reproduce the failure when debugging.

**Comment by thboileau** [comment]
thanks @bquintanaj, we received the JCA.
I have a look at the issue.

**Comment by thboileau** [comment]
Thanks a lot for your contribution!
I've integrated into the 2.3 branch also (which compiles fine). your fix will be part of next 2.3.10.
Regarding the master branch, I think I will have to spend a little bit of time on it in order to reduce gap with the 2.3.

**Comment by bquintanaj** [comment]
I see. I didn't try branch 2.3. Glad there's no such problem there.
Thank you very much for the help.

**Pull request merged**
