### PR TITLE
Correction of the unmap method

### PR DESCRIPTION
**Pull request by j-perrin**

### CODE REVIEW

**Comment by j-perrin** [comment]
correction of ArrayIndexOutOfBounds Exception

**Comment by thboileau** [comment]
Hello @j-perrin 

I'm very sorry for the late answer.
I would like to thank you a lot for your contribution. 
In order to integrate your contribution, do you mind to read the following and return the Joint Copyright Assignement at jlouvel@talend.com ? https://github.com/restlet/restlet-framework-java/wiki/Contribute#submit-contributions

**Comment by thboileau** [comment]
@j-perrin 
after discussion with Jérôme, Please, don't mind about the JCA. I'll apply the fix on the 2.4 and 2.5 branches. The fix will be shipped with the 2.4.3 and 2.5m1 versions

**Comment by thboileau** [comment]
@j-perrin 
after discussion with Jérôme, Please, don't mind about the JCA. I'll apply the fix on the 2.4 and 2.5 branches. The fix will be shipped with the 2.4.3 and 2.5m1 versions

2.4 PR https://github.com/restlet/restlet-framework-java/pull/1359
2.5 PR https://github.com/restlet/restlet-framework-java/pull/1360

**Pull request closed without merging**
