### PR TITLE
Don't clear current application before response is sent

### PR DESCRIPTION
**Pull request by rmbrad**
This PR adds a test for #1317 and fixes code so it passes.

### CODE REVIEW

**Comment by Tembrel** [comment]
I'm not sure about this PR. The current application is a thread-local static field, so the 5d459de commit could result in a reference to some application being kept around indefinitely.

How about arranging instead for the custom `ConnectorService` mentioned in #1317 to save and restore the current application in the same way that `ApplicationHelper.java` does?

https://github.com/restlet/restlet-framework-java/blob/6afed5c70ae36316af4cf471b077d219bc022a00/modules/org.restlet/src/org/restlet/engine/application/ApplicationHelper.java#L69-L82

**Comment by Tembrel** [comment]
I see the problem, and I see why you don't want to restore the current application with a value of `null`, but this PR then potentially introduces a different problem: If `current` is __not__ `null`, then any subsequent handling of the call after `ApplicationHelper.handle(Request, Response)` returns will be done with whatever application was current at the start of that call, which is not necessarily the same as `getHelped()`.

IIRC, some of this code was written in support of an effort to provide non-blocking connectors, where the handling of a single request might be spread across multiple threads. In that setting, it's crucial that any setting of a thread local be done with a save/restore such as the one in `ApplicationHelper`.

My sense is that the non-blocking connector effort has been dropped, in which case, maybe the save/restore logic isn't necessary at all. I think we need to hear from the designers at this point.

**Comment by rmbrad** [comment]
@Tembrel OK, I see. Thanks for the explanation. I guess I'll have to wait and see what the designers say.

**Comment by thomasjtaylor** [comment]
@Tembrel is there any progress on this issue? 2.3.12 still fails to call custom `ConnectorService`

**Comment by Tembrel** [comment]
Haven't heard from the designers, so I guess not.

**Comment by Tembrel** [comment]
As far as I know (which might not be that far), Restlet is still fundamentally designed for thread-per-request handling, so the kinds of things I worried about 3(!) years ago are moot, and it would be safe to merge this PR.

**Comment by thomasjtaylor** [comment]
@Tembrel Any chance we can get this merged for 2.4.4? We're running off of a fork and would like to get back on the main line.

**Comment by Tembrel** [comment]
Hmm, I didn't realize I could do the merge myself, but I pushed the button and it seems to have worked. @thomasjtaylor can you verify that I didn't break anything?

**Comment by thomasjtaylor** [comment]
@Tembrel I'll check it out. Thanks!

**Comment by thomasjtaylor** [comment]
@Tembrel seems to be working for us. I've rebased the fix for 2.4 in #1409.
We've been running the #1409 code with restlet 2.4.3 for the last two years.

**Pull request merged**
