### PR TITLE
Guice integration

### PR DESCRIPTION
**Pull request by Tembrel**
Added SelfInjectingServerResource and friends as an alternative to FinderFactory/RestletGuice.
See the [package README](https://github.com/Tembrel/restlet-framework-java/blob/guice-integration/incubator/org.restlet.ext.guice/README.md) for details.

This is my first pull request; please let me know what I've missed.

### CODE REVIEW

**Comment by kerbymart** [comment]
Hi @Tembrel can I ask how to use this for Restlet filters? 

The use case would be:

```java
public class AuthContextFilter extends Filter {
    
    @Inject
    AuthenticationService authenticationService;
    
    public AuthContextFilter(Context context) {
        super(context);
    }

    @Override
    protected int beforeHandle(Request request, Response response) {
        Series<Header> headers = (Series<Header>) request.getAttributes().get("org.restlet.http.headers");
        AuthContext authContext = new AuthContext(authenticationService, headers);
        request.getAttributes().put("authContext", authContext);
        return CONTINUE;
    }
}
```

**Comment by Tembrel** [comment]
The extension is only about injecting resources. There's a section at the end of this page that briefly discusses injection for other types:

https://restlet.talend.com/documentation/user-guide/2.4/extensions/guice

In your example, it might be simpler to set context explicitly, outside of injection:
```java
public class AuthContextFilter extends Filter {

    @Inject AuthenticationService authenticationService;
    
    // For use when injecting:
    @Inject AuthContextFilter() { super(null); }
    
    public AuthContextFilter(Context context) { super(context); }

    @Override protected int beforeHandle(Request request, Response response) {...}
}
```
An application wanting to wire an AuthContextFilter might look like this:
```java
public class MyApplication extends Application {
    @Inject Provider<AuthContextFilter> filterProvider;
    
    @Inject MyApplication(...) { ... }

    @Override public Restlet createInboundRoot() {
        Router router = ...;
        Filter filter = filterProvider.get();
        filter.setContext(getContext());
        filter.setNext(...);
        router.attach("some/path", filter);
        ...
        return router;
    }
}
```
If you don't like using `setContext`, you could use assisted injection, but that's a lot of machinery to avoid a single method call.

For the record, I __don't__ do this. I construct filters explicitly rather than injecting them, and I pass anything that would have been injected as a constructor parameter. That would look like this:
```java
public class MyApplication extends Application {

    @Inject AuthenticationService authenticationService;

    @Inject MyApplication(...) { ... }

    @Override public Restlet createInboundRoot() {
        Router router = ...;
        Filter filter = new AuthContextFilter(context, authenticationService);
        filter.setNext(...);
        router.attach("some/path", filter);
        ...
        return router;
    }
}
```
The drawback is that the application has to know about the AuthenticationService rather than keeping it private to the AuthContextFilter.

**Comment by kerbymart** [comment]
This is how I made it to work:

```java
public class MyApplication extends Application{

    private static final int HTTP_PORT = 8080;

    public static void main(final String[] args) throws Exception {
        Component component = new Component();
        component.getServers().add(Protocol.HTTP, HTTP_PORT);
        component.getDefaultHost().attach("", new MyApplication());
        component.start();
    }

    @Override
    public Restlet createInboundRoot() {
        Injector injector = RestletGuice.createInjector(
                new JpaModule(),
                new AuthModule(),
                new UserModule(),
                new SubscriptionModule()
        );
        
        FinderFactory finderFactory = injector.getInstance(FinderFactory.class);
        AuthenticationService authenticationService = injector.getInstance(AuthenticationService.class);

        Router router = new Router(getContext());

        router.attach("/hello", finderFactory.finder(HelloWorldResource.class));
        // ... other routes ...
        
        AuthContextFilter authContextFilter = new AuthContextFilter(getContext(), authenticationService);
        authContextFilter.setNext(router);

        CorsFilter corsFilter = new CorsFilter(getContext());
        corsFilter.setAllowedOrigins(new HashSet(Arrays.asList("*")));
        corsFilter.setSkippingResourceForCorsOptions(true);
        corsFilter.setNext(authContextFilter);

        return corsFilter;
    }
}
```

**Comment by Tembrel** [comment]
And note that you don't even need a `FinderFactory` if you subclass `SelfInjectingServerResource` for those resources that you want to inject. It's more minimalistic (and it's what I do). The only drawback is that you can't use constructor injection, just field and method injection.

**Pull request merged**
