### PR TITLE
Problem with case sensitivity of query parameters wit JAX-RS #1163

### PR DESCRIPTION
**Pull request by gartcimore**

### CODE REVIEW

**Comment by thboileau** [comment]
Hi @gartcimore, we know its a bit of a pain but do you mind sending us a signed JCA?
https://github.com/restlet/restlet-framework-java/wiki/Contribute

**Comment by thboileau** [comment]
thanks @gartcimore! we've received the signed JCA.

**Comment by thboileau** [comment]
thanks a lot @gartcimore for your contribution!

**Comment by gartcimore** [comment]
with great pleasure

**Pull request merged**
